// <auto-generated />
namespace Heeelp.Core.DataBase.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Azure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Azure));
        
        string IMigrationMetadata.Id
        {
            get { return "201602042324346_Azure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
